---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  vars:
    apache_mods_enabled:
      - "ssl"
    apache_create_vhosts: true
    apache_vhosts_filename: "mysite.conf"
    apache_vhost_config:
      - listen_ip: "*"
        listen_port: 80
        server_name: host1
        serveralias: alias1
        documentroot: "/var/www/html"
        serveradmin: "admin@localhost"
        custom_param: |
        error_log_param: ${APACHE_LOG_DIR}/error.log
        custom_log_param: ${APACHE_LOG_DIR}/access.log combined"
        log_level: "warn"
        directory:
          - path: "/var/www/html"

  roles:
    - role: .
